### ISSUE TITLE
Duplicated import

### ISSUE THREAD

**Issue by maciekpaprocki** [jonathantneal/postcss-partial-import#28]
I think it would be good to have option to ignore all next imports of this same file. It might change current behaviour, however in CSS if you are including twice this same file your are probably doing something wrong as size of the file might increase drastically. Example:

**module1.css requires css library:**

``` css
@import 'somelibrary';
.Module1{
   something:something;
}
```

**module2.css requires also css library**

``` css
@import 'somelibrary';
.Module2{
   something:something;
}
```

**index.css require module1 and module2, but shouldn't care about some library.** 

``` css
@import 'module1';
@import 'module2';
```

I could work on PR for that. 

Good option would be to allow some force option like `@import 'somefile' !important;` which will force re-adding file, as well as extra check if this same text wasn't included from different path. like for example  if reset.css is not included twice from local and from node_modules.
